# OAuth credential for the Twitter API
consumer_key: PUT_YOUR_AUTHENTICATION_INFO_HERE
consumer_secret: PUT_YOUR_AUTHENTICATION_INFO_HERE
oauth_token: PUT_YOUR_AUTHENTICATION_INFO_HERE
oauth_secret: PUT_YOUR_AUTHENTICATION_INFO_HERE

# URL of the Twitter API for the keyword search stream
url_filter: https://stream.twitter.com/1.1/statuses/filter.json
